name: Deployment for Vue application

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'  # unbedingt eine Node-Version angeben

      - name: Install packages
        run: npm install  # schneller & sauberer als npm i

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: dist  # ./dist oder dist ist gleichwertig
